spring:
  datasource:
    username: root
    password: yxd,2022
    url: jdbc:mysql://101.43.52.197:3306/db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=GMT%2b8&characterEncoding=utf8&connectTimeout=1000&socketTimeout=15000&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
